#! /bin/sh

set -e

VDIR=/var/lib/cfengine3

if [ "$1" = "purge" ]; then
    if [ -d "$VDIR" ]; then
	cd "$VDIR"
	find . -mindepth 1 -maxdepth 1 \
	    -name inputs -prune -o -print0 | xargs -0r rm -rf
	cd /; rmdir "$VDIR"
    fi
    rm -f /etc/default/cfengine3
fi

#DEBHELPER#
